set(cancun_excluded_tests
    # EIP-4844 block validation: Need access to parent header
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_excess_blob_gas_above_target_change.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_excess_blob_gas_change.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/fork_transition_excess_blob_gas.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_excess_blob_gas_target_blobs_increase_from_zero.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_non_multiple_excess_blob_gas.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_zero_excess_blob_gas_in_header.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/correct_excess_blob_gas_calculation.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_excess_blob_gas_above_target_change.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_static_excess_blob_gas_from_zero_on_blobs_above_target.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_static_excess_blob_gas.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_negative_excess_blob_gas.json"
    "BlockchainTests.GeneralStateTests/Pyspecs/cancun/eip4844_blobs/invalid_excess_blob_gas_change.json"
    "BlockchainTests.cancun/eip4844_blobs/excess_blob_gas/invalid_static_excess_blob_gas.json"
    "BlockchainTests.cancun/eip4844_blobs/excess_blob_gas/invalid_non_multiple_excess_blob_gas.json"
    "BlockchainTests.cancun/eip4844_blobs/excess_blob_gas/invalid_static_excess_blob_gas_from_zero_on_blobs_above_target.json"
    "BlockchainTests.cancun/eip4844_blobs/excess_blob_gas/invalid_excess_blob_gas_above_target_change.json"
    "BlockchainTests.cancun/eip4844_blobs/excess_blob_gas/invalid_excess_blob_gas_change.json"
    "BlockchainTests.cancun/eip4844_blobs/excess_blob_gas/invalid_excess_blob_gas_target_blobs_increase_from_zero.json"
    "BlockchainTests.cancun/eip4844_blobs/excess_blob_gas/invalid_negative_excess_blob_gas.json"
    "BlockchainTests.cancun/eip4844_blobs/excess_blob_gas/invalid_zero_excess_blob_gas_in_header.json"

    # withdrawals root
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/incorrectWithdrawalsRoot.json"

    # EIP-1559
    "BlockchainTests.InvalidBlocks/bcEIP1559/badBlocks.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/badUncles.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/baseFee.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/checkGasLimit.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/feeCap.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/gasLimit20m.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/gasLimit40m.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/intrinsicOrFail.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/transFail.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/valCausesOOF.json"

    # Stricter validation
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/accountInteractions.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/badBlocks.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/badUncles.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/baseFee.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/checkGasLimit.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/feeCap.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/gasLimit20m.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/gasLimit40m.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/intrinsicOrFail.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/transFail.json"
    "BlockchainTests.InvalidBlocks/bcEIP1559/valCausesOOF.json"
    "BlockchainTests.InvalidBlocks/bcEIP3675/timestampPerBlock.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/badTimestamp.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/timeDiff0.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongCoinbase.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongGasLimit.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongParentHash.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongParentHash2.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongReceiptTrie.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongStateRoot.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongTimestamp.json"
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongTransactionsTrie.json"
    "BlockchainTests.InvalidBlocks/bcMultiChainTest/UncleFromSideChain.json"
    "BlockchainTests.InvalidBlocks/bcStateTests/CreateTransactionReverted.json"
    "BlockchainTests.InvalidBlocks/bcStateTests/RefundOverflow.json"
    "BlockchainTests.InvalidBlocks/bcStateTests/RefundOverflow2.json"
    "BlockchainTests.InvalidBlocks/bcStateTests/callcodeOutput2.json"
    "BlockchainTests.InvalidBlocks/bcStateTests/createNameRegistratorPerTxsNotEnoughGasAt.json"
    "BlockchainTests.InvalidBlocks/bcStateTests/dataTx.json"

    # Slow + stack-heavy tests
    "BlockchainTests.GeneralStateTests/stBadOpcode/*"
    "BlockchainTests.GeneralStateTests/stBugs/*"
    "BlockchainTests.GeneralStateTests/stCallCodes/*"
    "BlockchainTests.GeneralStateTests/stCallCreateCallCodeTest/*"
    "BlockchainTests.GeneralStateTests/stCallDelegateCodesCallCodeHomestead/*"
    "BlockchainTests.GeneralStateTests/stCallDelegateCodesHomestead/*"
    "BlockchainTests.GeneralStateTests/stCreate2/*"
    "BlockchainTests.GeneralStateTests/stCreateTest/*"

    # misc
    "BlockchainTests.GeneralStateTests/stCreate2/RevertInCreateInInitCreate2Paris.json"
    "BlockchainTests.GeneralStateTests/stCreate2/create2collisionStorageParis.json"
    "BlockchainTests.GeneralStateTests/stExtCodeHash/dynamicAccountOverwriteEmpty_Paris.json"
    "BlockchainTests.GeneralStateTests/stRevertTest/RevertInCreateInInit_Paris.json"
    "BlockchainTests.GeneralStateTests/stSStoreTest/InitCollisionParis.json")
