set(shanghai_excluded_tests
    "BlockchainTests.GeneralStateTests/stTransactionTest/ValueOverflow.json" # RLP
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/withdrawalsAddressBounds.json" # RLP
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/withdrawalsAmountBounds.json" # RLP
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/withdrawalsIndexBounds.json"  # RLP
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/withdrawalsRLPlessElements.json" # RLP
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/withdrawalsRLPnotAList.json" # RLP
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/withdrawalsValidatorIndexBounds.json" # RLP
    "GeneralStateTests.stCreate2/RevertInCreateInInitCreate2.json" # Incarnation
    "GeneralStateTests.stCreate2/create2collisionStorage.json" # Incarnation
    "GeneralStateTests.stExtCodeHash/dynamicAccountOverwriteEmpty.json" # Incarnation
    "GeneralStateTests.stRevertTest/RevertInCreateInInit.json" # Incarnation
    "GeneralStateTests.stSStoreTest/InitCollision.json" # Incarnation
    "BlockchainTests.GeneralStateTests/stCreate2/RevertInCreateInInitCreate2.json" # Incarnation
    "BlockchainTests.GeneralStateTests/stCreate2/create2collisionStorage.json" # Incarnation
    "BlockchainTests.GeneralStateTests/stEIP1559/lowGasLimit.json" # ParentHeader
    "BlockchainTests.GeneralStateTests/stExtCodeHash/dynamicAccountOverwriteEmpty.json" # Incarnation
    "BlockchainTests.GeneralStateTests/stRevertTest/RevertInCreateInInit.json" # Incarnation
    "BlockchainTests.GeneralStateTests/stSStoreTest/InitCollision.json" # Incarnation
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/incorrectWithdrawalsRoot.json" # Trie
    "BlockchainTests.InvalidBlocks/bc4895_withdrawals/withdrawalsRLPmoreElements.json" # RLP
    "BlockchainTests.InvalidBlocks/bcEIP1559/badBlocks.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcEIP1559/badUncles.json" # Mixed
    "BlockchainTests.InvalidBlocks/bcEIP1559/gasLimit20m.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcEIP1559/gasLimit40m.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcEIP3675/timestampPerBlock.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/badTimestamp.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/timeDiff0.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongCoinbase.json" # StateRoot
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongGasLimit.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongParentHash.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongParentHash2.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongReceiptTrie.json" # Trie
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongStateRoot.json" # StateRoot
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongTimestamp.json" # ParentHeader
    "BlockchainTests.InvalidBlocks/bcInvalidHeaderTest/wrongTransactionsTrie.json" # Trie
    "BlockchainTests.InvalidBlocks/bcMultiChainTest/UncleFromSideChain.json" # Uncle
    "BlockchainTests.ValidBlocks/bcStateTests/suicideStorageCheck.json" # Incarnation
    "BlockchainTests.ValidBlocks/bcStateTests/suicideStorageCheckVCreate.json" # Incarnation
    "BlockchainTests.ValidBlocks/bcStateTests/suicideStorageCheckVCreate2.json" # Incarnation
    "BlockchainTests.ValidBlocks/bcStateTests/suicideThenCheckBalance.json" # Incarnation
)
