#pragma once

#ifdef ON_EVM_OPCODE
static_assert(
    false, "ON_EVM_OPCODE macro predefined when including EVM opcode xmacro");
#endif

#ifdef EVM_ALL_OPCODES
static_assert(false, "EVM_ALL_OPCODES macro already defined");
#endif

#define EVM_ALL_OPCODES                                                        \
    ON_EVM_OPCODE(0x00)                                                        \
    ON_EVM_OPCODE(0x01)                                                        \
    ON_EVM_OPCODE(0x02)                                                        \
    ON_EVM_OPCODE(0x03)                                                        \
    ON_EVM_OPCODE(0x04)                                                        \
    ON_EVM_OPCODE(0x05)                                                        \
    ON_EVM_OPCODE(0x06)                                                        \
    ON_EVM_OPCODE(0x07)                                                        \
    ON_EVM_OPCODE(0x08)                                                        \
    ON_EVM_OPCODE(0x09)                                                        \
    ON_EVM_OPCODE(0x0A)                                                        \
    ON_EVM_OPCODE(0x0B)                                                        \
    ON_EVM_OPCODE(0x0C)                                                        \
    ON_EVM_OPCODE(0x0D)                                                        \
    ON_EVM_OPCODE(0x0E)                                                        \
    ON_EVM_OPCODE(0x0F)                                                        \
    ON_EVM_OPCODE(0x10)                                                        \
    ON_EVM_OPCODE(0x11)                                                        \
    ON_EVM_OPCODE(0x12)                                                        \
    ON_EVM_OPCODE(0x13)                                                        \
    ON_EVM_OPCODE(0x14)                                                        \
    ON_EVM_OPCODE(0x15)                                                        \
    ON_EVM_OPCODE(0x16)                                                        \
    ON_EVM_OPCODE(0x17)                                                        \
    ON_EVM_OPCODE(0x18)                                                        \
    ON_EVM_OPCODE(0x19)                                                        \
    ON_EVM_OPCODE(0x1A)                                                        \
    ON_EVM_OPCODE(0x1B)                                                        \
    ON_EVM_OPCODE(0x1C)                                                        \
    ON_EVM_OPCODE(0x1D)                                                        \
    ON_EVM_OPCODE(0x1E)                                                        \
    ON_EVM_OPCODE(0x1F)                                                        \
    ON_EVM_OPCODE(0x20)                                                        \
    ON_EVM_OPCODE(0x21)                                                        \
    ON_EVM_OPCODE(0x22)                                                        \
    ON_EVM_OPCODE(0x23)                                                        \
    ON_EVM_OPCODE(0x24)                                                        \
    ON_EVM_OPCODE(0x25)                                                        \
    ON_EVM_OPCODE(0x26)                                                        \
    ON_EVM_OPCODE(0x27)                                                        \
    ON_EVM_OPCODE(0x28)                                                        \
    ON_EVM_OPCODE(0x29)                                                        \
    ON_EVM_OPCODE(0x2A)                                                        \
    ON_EVM_OPCODE(0x2B)                                                        \
    ON_EVM_OPCODE(0x2C)                                                        \
    ON_EVM_OPCODE(0x2D)                                                        \
    ON_EVM_OPCODE(0x2E)                                                        \
    ON_EVM_OPCODE(0x2F)                                                        \
    ON_EVM_OPCODE(0x30)                                                        \
    ON_EVM_OPCODE(0x31)                                                        \
    ON_EVM_OPCODE(0x32)                                                        \
    ON_EVM_OPCODE(0x33)                                                        \
    ON_EVM_OPCODE(0x34)                                                        \
    ON_EVM_OPCODE(0x35)                                                        \
    ON_EVM_OPCODE(0x36)                                                        \
    ON_EVM_OPCODE(0x37)                                                        \
    ON_EVM_OPCODE(0x38)                                                        \
    ON_EVM_OPCODE(0x39)                                                        \
    ON_EVM_OPCODE(0x3A)                                                        \
    ON_EVM_OPCODE(0x3B)                                                        \
    ON_EVM_OPCODE(0x3C)                                                        \
    ON_EVM_OPCODE(0x3D)                                                        \
    ON_EVM_OPCODE(0x3E)                                                        \
    ON_EVM_OPCODE(0x3F)                                                        \
    ON_EVM_OPCODE(0x40)                                                        \
    ON_EVM_OPCODE(0x41)                                                        \
    ON_EVM_OPCODE(0x42)                                                        \
    ON_EVM_OPCODE(0x43)                                                        \
    ON_EVM_OPCODE(0x44)                                                        \
    ON_EVM_OPCODE(0x45)                                                        \
    ON_EVM_OPCODE(0x46)                                                        \
    ON_EVM_OPCODE(0x47)                                                        \
    ON_EVM_OPCODE(0x48)                                                        \
    ON_EVM_OPCODE(0x49)                                                        \
    ON_EVM_OPCODE(0x4A)                                                        \
    ON_EVM_OPCODE(0x4B)                                                        \
    ON_EVM_OPCODE(0x4C)                                                        \
    ON_EVM_OPCODE(0x4D)                                                        \
    ON_EVM_OPCODE(0x4E)                                                        \
    ON_EVM_OPCODE(0x4F)                                                        \
    ON_EVM_OPCODE(0x50)                                                        \
    ON_EVM_OPCODE(0x51)                                                        \
    ON_EVM_OPCODE(0x52)                                                        \
    ON_EVM_OPCODE(0x53)                                                        \
    ON_EVM_OPCODE(0x54)                                                        \
    ON_EVM_OPCODE(0x55)                                                        \
    ON_EVM_OPCODE(0x56)                                                        \
    ON_EVM_OPCODE(0x57)                                                        \
    ON_EVM_OPCODE(0x58)                                                        \
    ON_EVM_OPCODE(0x59)                                                        \
    ON_EVM_OPCODE(0x5A)                                                        \
    ON_EVM_OPCODE(0x5B)                                                        \
    ON_EVM_OPCODE(0x5C)                                                        \
    ON_EVM_OPCODE(0x5D)                                                        \
    ON_EVM_OPCODE(0x5E)                                                        \
    ON_EVM_OPCODE(0x5F)                                                        \
    ON_EVM_OPCODE(0x60)                                                        \
    ON_EVM_OPCODE(0x61)                                                        \
    ON_EVM_OPCODE(0x62)                                                        \
    ON_EVM_OPCODE(0x63)                                                        \
    ON_EVM_OPCODE(0x64)                                                        \
    ON_EVM_OPCODE(0x65)                                                        \
    ON_EVM_OPCODE(0x66)                                                        \
    ON_EVM_OPCODE(0x67)                                                        \
    ON_EVM_OPCODE(0x68)                                                        \
    ON_EVM_OPCODE(0x69)                                                        \
    ON_EVM_OPCODE(0x6A)                                                        \
    ON_EVM_OPCODE(0x6B)                                                        \
    ON_EVM_OPCODE(0x6C)                                                        \
    ON_EVM_OPCODE(0x6D)                                                        \
    ON_EVM_OPCODE(0x6E)                                                        \
    ON_EVM_OPCODE(0x6F)                                                        \
    ON_EVM_OPCODE(0x70)                                                        \
    ON_EVM_OPCODE(0x71)                                                        \
    ON_EVM_OPCODE(0x72)                                                        \
    ON_EVM_OPCODE(0x73)                                                        \
    ON_EVM_OPCODE(0x74)                                                        \
    ON_EVM_OPCODE(0x75)                                                        \
    ON_EVM_OPCODE(0x76)                                                        \
    ON_EVM_OPCODE(0x77)                                                        \
    ON_EVM_OPCODE(0x78)                                                        \
    ON_EVM_OPCODE(0x79)                                                        \
    ON_EVM_OPCODE(0x7A)                                                        \
    ON_EVM_OPCODE(0x7B)                                                        \
    ON_EVM_OPCODE(0x7C)                                                        \
    ON_EVM_OPCODE(0x7D)                                                        \
    ON_EVM_OPCODE(0x7E)                                                        \
    ON_EVM_OPCODE(0x7F)                                                        \
    ON_EVM_OPCODE(0x80)                                                        \
    ON_EVM_OPCODE(0x81)                                                        \
    ON_EVM_OPCODE(0x82)                                                        \
    ON_EVM_OPCODE(0x83)                                                        \
    ON_EVM_OPCODE(0x84)                                                        \
    ON_EVM_OPCODE(0x85)                                                        \
    ON_EVM_OPCODE(0x86)                                                        \
    ON_EVM_OPCODE(0x87)                                                        \
    ON_EVM_OPCODE(0x88)                                                        \
    ON_EVM_OPCODE(0x89)                                                        \
    ON_EVM_OPCODE(0x8A)                                                        \
    ON_EVM_OPCODE(0x8B)                                                        \
    ON_EVM_OPCODE(0x8C)                                                        \
    ON_EVM_OPCODE(0x8D)                                                        \
    ON_EVM_OPCODE(0x8E)                                                        \
    ON_EVM_OPCODE(0x8F)                                                        \
    ON_EVM_OPCODE(0x90)                                                        \
    ON_EVM_OPCODE(0x91)                                                        \
    ON_EVM_OPCODE(0x92)                                                        \
    ON_EVM_OPCODE(0x93)                                                        \
    ON_EVM_OPCODE(0x94)                                                        \
    ON_EVM_OPCODE(0x95)                                                        \
    ON_EVM_OPCODE(0x96)                                                        \
    ON_EVM_OPCODE(0x97)                                                        \
    ON_EVM_OPCODE(0x98)                                                        \
    ON_EVM_OPCODE(0x99)                                                        \
    ON_EVM_OPCODE(0x9A)                                                        \
    ON_EVM_OPCODE(0x9B)                                                        \
    ON_EVM_OPCODE(0x9C)                                                        \
    ON_EVM_OPCODE(0x9D)                                                        \
    ON_EVM_OPCODE(0x9E)                                                        \
    ON_EVM_OPCODE(0x9F)                                                        \
    ON_EVM_OPCODE(0xA0)                                                        \
    ON_EVM_OPCODE(0xA1)                                                        \
    ON_EVM_OPCODE(0xA2)                                                        \
    ON_EVM_OPCODE(0xA3)                                                        \
    ON_EVM_OPCODE(0xA4)                                                        \
    ON_EVM_OPCODE(0xA5)                                                        \
    ON_EVM_OPCODE(0xA6)                                                        \
    ON_EVM_OPCODE(0xA7)                                                        \
    ON_EVM_OPCODE(0xA8)                                                        \
    ON_EVM_OPCODE(0xA9)                                                        \
    ON_EVM_OPCODE(0xAA)                                                        \
    ON_EVM_OPCODE(0xAB)                                                        \
    ON_EVM_OPCODE(0xAC)                                                        \
    ON_EVM_OPCODE(0xAD)                                                        \
    ON_EVM_OPCODE(0xAE)                                                        \
    ON_EVM_OPCODE(0xAF)                                                        \
    ON_EVM_OPCODE(0xB0)                                                        \
    ON_EVM_OPCODE(0xB1)                                                        \
    ON_EVM_OPCODE(0xB2)                                                        \
    ON_EVM_OPCODE(0xB3)                                                        \
    ON_EVM_OPCODE(0xB4)                                                        \
    ON_EVM_OPCODE(0xB5)                                                        \
    ON_EVM_OPCODE(0xB6)                                                        \
    ON_EVM_OPCODE(0xB7)                                                        \
    ON_EVM_OPCODE(0xB8)                                                        \
    ON_EVM_OPCODE(0xB9)                                                        \
    ON_EVM_OPCODE(0xBA)                                                        \
    ON_EVM_OPCODE(0xBB)                                                        \
    ON_EVM_OPCODE(0xBC)                                                        \
    ON_EVM_OPCODE(0xBD)                                                        \
    ON_EVM_OPCODE(0xBE)                                                        \
    ON_EVM_OPCODE(0xBF)                                                        \
    ON_EVM_OPCODE(0xC0)                                                        \
    ON_EVM_OPCODE(0xC1)                                                        \
    ON_EVM_OPCODE(0xC2)                                                        \
    ON_EVM_OPCODE(0xC3)                                                        \
    ON_EVM_OPCODE(0xC4)                                                        \
    ON_EVM_OPCODE(0xC5)                                                        \
    ON_EVM_OPCODE(0xC6)                                                        \
    ON_EVM_OPCODE(0xC7)                                                        \
    ON_EVM_OPCODE(0xC8)                                                        \
    ON_EVM_OPCODE(0xC9)                                                        \
    ON_EVM_OPCODE(0xCA)                                                        \
    ON_EVM_OPCODE(0xCB)                                                        \
    ON_EVM_OPCODE(0xCC)                                                        \
    ON_EVM_OPCODE(0xCD)                                                        \
    ON_EVM_OPCODE(0xCE)                                                        \
    ON_EVM_OPCODE(0xCF)                                                        \
    ON_EVM_OPCODE(0xD0)                                                        \
    ON_EVM_OPCODE(0xD1)                                                        \
    ON_EVM_OPCODE(0xD2)                                                        \
    ON_EVM_OPCODE(0xD3)                                                        \
    ON_EVM_OPCODE(0xD4)                                                        \
    ON_EVM_OPCODE(0xD5)                                                        \
    ON_EVM_OPCODE(0xD6)                                                        \
    ON_EVM_OPCODE(0xD7)                                                        \
    ON_EVM_OPCODE(0xD8)                                                        \
    ON_EVM_OPCODE(0xD9)                                                        \
    ON_EVM_OPCODE(0xDA)                                                        \
    ON_EVM_OPCODE(0xDB)                                                        \
    ON_EVM_OPCODE(0xDC)                                                        \
    ON_EVM_OPCODE(0xDD)                                                        \
    ON_EVM_OPCODE(0xDE)                                                        \
    ON_EVM_OPCODE(0xDF)                                                        \
    ON_EVM_OPCODE(0xE0)                                                        \
    ON_EVM_OPCODE(0xE1)                                                        \
    ON_EVM_OPCODE(0xE2)                                                        \
    ON_EVM_OPCODE(0xE3)                                                        \
    ON_EVM_OPCODE(0xE4)                                                        \
    ON_EVM_OPCODE(0xE5)                                                        \
    ON_EVM_OPCODE(0xE6)                                                        \
    ON_EVM_OPCODE(0xE7)                                                        \
    ON_EVM_OPCODE(0xE8)                                                        \
    ON_EVM_OPCODE(0xE9)                                                        \
    ON_EVM_OPCODE(0xEA)                                                        \
    ON_EVM_OPCODE(0xEB)                                                        \
    ON_EVM_OPCODE(0xEC)                                                        \
    ON_EVM_OPCODE(0xED)                                                        \
    ON_EVM_OPCODE(0xEE)                                                        \
    ON_EVM_OPCODE(0xEF)                                                        \
    ON_EVM_OPCODE(0xF0)                                                        \
    ON_EVM_OPCODE(0xF1)                                                        \
    ON_EVM_OPCODE(0xF2)                                                        \
    ON_EVM_OPCODE(0xF3)                                                        \
    ON_EVM_OPCODE(0xF4)                                                        \
    ON_EVM_OPCODE(0xF5)                                                        \
    ON_EVM_OPCODE(0xF6)                                                        \
    ON_EVM_OPCODE(0xF7)                                                        \
    ON_EVM_OPCODE(0xF8)                                                        \
    ON_EVM_OPCODE(0xF9)                                                        \
    ON_EVM_OPCODE(0xFA)                                                        \
    ON_EVM_OPCODE(0xFB)                                                        \
    ON_EVM_OPCODE(0xFC)                                                        \
    ON_EVM_OPCODE(0xFD)                                                        \
    ON_EVM_OPCODE(0xFE)                                                        \
    ON_EVM_OPCODE(0xFF)
