#pragma once

#include <monad/config.hpp>

MONAD_NAMESPACE_BEGIN

enum class ValidationStatus
{
    SUCCESS,

    // Block Validation Error
    GAS_ABOVE_LIMIT,
    INVALID_GAS_LIMIT,
    EXTRA_DATA_TOO_LONG,
    WRONG_OMMERS_HASH,
    FIELD_BEFORE_FORK,
    MISSING_FIELD,
    POW_BLOCK_AFTER_MERGE,
    INVALID_NONCE,
    TOO_MANY_OMMERS,
    DUPLICATE_OMMERS,
    INVALID_OMMER_HEADER,
    WRONG_DAO_EXTRA_DATA,

    // Transaction Validation Error
    INSUFFICIENT_BALANCE,
    INTRINSIC_GAS_GREATER_THAN_LIMIT,
    BAD_NONCE,
    SENDER_NOT_EOA,
    TYPE_NOT_SUPPORTED,
    MAX_FEE_LESS_THAN_BASE,
    PRIORITY_FEE_GREATER_THAN_MAX,
    NONCE_EXCEEDS_MAX,
    INIT_CODE_LIMIT_EXCEEDED,
    GAS_LIMIT_REACHED,
    WRONG_CHAIN_ID,
    MISSING_SENDER,

};

MONAD_NAMESPACE_END
