// Copyright (C) 2025 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// WARNING: THIS FILE CONTAINS GENERATED CODE, DO NOT EDIT MANUALLY! If
// you need changes, change the code generator or its inputs instead. This
// file was generated by running the following command:
//
//    util/ctypes/codegen/cg-ctypes -s category/execution/ctypes c -p
//    /home/ken/src/monad -fclang-format-19

#include <stdint.h>

#include <category/core/event/event_metadata.h>
#include <category/execution/ethereum/event/exec_event_ctypes.h>

#ifdef __cplusplus
extern "C"
{
#endif

struct monad_event_metadata const g_monad_exec_event_metadata[25] = {

    [MONAD_EXEC_NONE] =
        {.event_type = MONAD_EXEC_NONE,
         .c_name = "NONE",
         .description = "Reserved code so that 0 remains invalid"},

    [MONAD_EXEC_RECORD_ERROR] =
        {.event_type = MONAD_EXEC_RECORD_ERROR,
         .c_name = "RECORD_ERROR",
         .description = "Reserved event type used for recording errors"},

    [MONAD_EXEC_BLOCK_START] =
        {.event_type = MONAD_EXEC_BLOCK_START,
         .c_name = "BLOCK_START",
         .description = "Event recorded at the start of EVM execution"},

    [MONAD_EXEC_BLOCK_REJECT] =
        {.event_type = MONAD_EXEC_BLOCK_REJECT,
         .c_name = "BLOCK_REJECT",
         .description =
             "Event recorded when a block is rejected (i.e., is invalid)"},

    [MONAD_EXEC_BLOCK_PERF_EVM_ENTER] =
        {.event_type = MONAD_EXEC_BLOCK_PERF_EVM_ENTER,
         .c_name = "BLOCK_PERF_EVM_ENTER",
         .description =
             "Performance marker event recorded at the start of core EVM "
             "execution (after validation and sender recovery)"},

    [MONAD_EXEC_BLOCK_PERF_EVM_EXIT] =
        {.event_type = MONAD_EXEC_BLOCK_PERF_EVM_EXIT,
         .c_name = "BLOCK_PERF_EVM_EXIT",
         .description = "Performance marker event recorded when all "
                        "transaction execution is finished"},

    [MONAD_EXEC_BLOCK_END] =
        {.event_type = MONAD_EXEC_BLOCK_END,
         .c_name = "BLOCK_END",
         .description = "Event recorded upon successful block execution"},

    [MONAD_EXEC_BLOCK_QC] =
        {.event_type = MONAD_EXEC_BLOCK_QC,
         .c_name = "BLOCK_QC",
         .description = "Event recorded when a proposed block obtains a quorum "
                        "certificate"},

    [MONAD_EXEC_BLOCK_FINALIZED] =
        {.event_type = MONAD_EXEC_BLOCK_FINALIZED,
         .c_name = "BLOCK_FINALIZED",
         .description = "Event recorded when consensus finalizes a block"},

    [MONAD_EXEC_BLOCK_VERIFIED] =
        {.event_type = MONAD_EXEC_BLOCK_VERIFIED,
         .c_name = "BLOCK_VERIFIED",
         .description = "Event recorded when consensus verifies the state root "
                        "of a finalized block"},

    [MONAD_EXEC_TXN_HEADER_START] =
        {.event_type = MONAD_EXEC_TXN_HEADER_START,
         .c_name = "TXN_HEADER_START",
         .description =
             "First event recorded when transaction processing starts"},

    [MONAD_EXEC_TXN_ACCESS_LIST_ENTRY] =
        {.event_type = MONAD_EXEC_TXN_ACCESS_LIST_ENTRY,
         .c_name = "TXN_ACCESS_LIST_ENTRY",
         .description = "Entry in an EIP-2930 storage access warmup list"},

    [MONAD_EXEC_TXN_AUTH_LIST_ENTRY] =
        {.event_type = MONAD_EXEC_TXN_AUTH_LIST_ENTRY,
         .c_name = "TXN_AUTH_LIST_ENTRY",
         .description = "Entry in an EIP-7702 authorization list"},

    [MONAD_EXEC_TXN_HEADER_END] =
        {.event_type = MONAD_EXEC_TXN_HEADER_END,
         .c_name = "TXN_HEADER_END",
         .description = "Marker event recorded after all transaction header "
                        "events are emitted"},

    [MONAD_EXEC_TXN_REJECT] =
        {.event_type = MONAD_EXEC_TXN_REJECT,
         .c_name = "TXN_REJECT",
         .description = "Event recorded when a transaction is rejected (i.e., "
                        "is invalid)"},

    [MONAD_EXEC_TXN_PERF_EVM_ENTER] =
        {.event_type = MONAD_EXEC_TXN_PERF_EVM_ENTER,
         .c_name = "TXN_PERF_EVM_ENTER",
         .description = "Performance marker event recorded at the start of EVM "
                        "execution (after sender recovery)"},

    [MONAD_EXEC_TXN_PERF_EVM_EXIT] =
        {.event_type = MONAD_EXEC_TXN_PERF_EVM_EXIT,
         .c_name = "TXN_PERF_EVM_EXIT",
         .description =
             "Performance marker event recorded at the end of EVM execution"},

    [MONAD_EXEC_TXN_EVM_OUTPUT] =
        {.event_type = MONAD_EXEC_TXN_EVM_OUTPUT,
         .c_name = "TXN_EVM_OUTPUT",
         .description = "Event recorded when transaction execution halts."},

    [MONAD_EXEC_TXN_LOG] =
        {.event_type = MONAD_EXEC_TXN_LOG,
         .c_name = "TXN_LOG",
         .description = "Event recorded when a transaction emits a LOG"},

    [MONAD_EXEC_TXN_CALL_FRAME] =
        {.event_type = MONAD_EXEC_TXN_CALL_FRAME,
         .c_name = "TXN_CALL_FRAME",
         .description = "Event recorded when a call frame is emitted."},

    [MONAD_EXEC_TXN_END] =
        {.event_type = MONAD_EXEC_TXN_END,
         .c_name = "TXN_END",
         .description =
             "Event recorded to mark the end of events for this transaction"},

    [MONAD_EXEC_ACCOUNT_ACCESS_LIST_HEADER] =
        {.event_type = MONAD_EXEC_ACCOUNT_ACCESS_LIST_HEADER,
         .c_name = "ACCOUNT_ACCESS_LIST_HEADER",
         .description = "Header event that precedes a variably-sized list of "
                        "account_access objects"},

    [MONAD_EXEC_ACCOUNT_ACCESS] =
        {.event_type = MONAD_EXEC_ACCOUNT_ACCESS,
         .c_name = "ACCOUNT_ACCESS",
         .description = "Event emitted when an account is read or written"},

    [MONAD_EXEC_STORAGE_ACCESS] =
        {.event_type = MONAD_EXEC_STORAGE_ACCESS,
         .c_name = "STORAGE_ACCESS",
         .description =
             "Event emitted for each account storage key that is accessed"},

    [MONAD_EXEC_EVM_ERROR] =
        {.event_type = MONAD_EXEC_EVM_ERROR,
         .c_name = "EVM_ERROR",
         .description =
             "Error occurred in execution process (not a validation error)"},
};

uint8_t const g_monad_exec_event_schema_hash[32] = {
    0x89, 0x33, 0xf9, 0x07, 0xc4, 0x32, 0xc9, 0x8a, 0xc0, 0xc8, 0xdb,
    0x62, 0xf9, 0xaa, 0x16, 0x4c, 0x0c, 0x3f, 0x16, 0x72, 0xf4, 0x12,
    0x90, 0xe4, 0xea, 0x34, 0x08, 0xdf, 0x6c, 0x67, 0x23, 0xf3,
};

#ifdef __cplusplus
} // extern "C"
#endif
