// Copyright (C) 2025 Category Labs, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

#pragma once

#ifdef MONAD_COMPILER_ON_EVM_OPCODE
static_assert(
    false, "MONAD_COMPILER_ON_EVM_OPCODE macro predefined when including EVM "
           "opcode xmacro");
#endif

#ifdef MONAD_COMPILER_EVM_ALL_OPCODES
static_assert(false, "MONAD_COMPILER_EVM_ALL_OPCODES macro already defined");
#endif

#define MONAD_COMPILER_EVM_ALL_OPCODES                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x00)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x01)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x02)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x03)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x04)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x05)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x06)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x07)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x08)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x09)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x0A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x0B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x0C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x0D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x0E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x0F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x10)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x11)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x12)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x13)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x14)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x15)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x16)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x17)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x18)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x19)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x1A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x1B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x1C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x1D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x1E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x1F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x20)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x21)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x22)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x23)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x24)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x25)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x26)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x27)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x28)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x29)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x2A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x2B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x2C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x2D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x2E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x2F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x30)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x31)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x32)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x33)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x34)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x35)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x36)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x37)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x38)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x39)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x3A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x3B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x3C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x3D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x3E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x3F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x40)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x41)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x42)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x43)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x44)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x45)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x46)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x47)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x48)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x49)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x4A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x4B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x4C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x4D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x4E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x4F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x50)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x51)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x52)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x53)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x54)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x55)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x56)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x57)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x58)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x59)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x5A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x5B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x5C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x5D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x5E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x5F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x60)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x61)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x62)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x63)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x64)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x65)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x66)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x67)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x68)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x69)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x6A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x6B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x6C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x6D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x6E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x6F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x70)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x71)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x72)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x73)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x74)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x75)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x76)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x77)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x78)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x79)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x7A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x7B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x7C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x7D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x7E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x7F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x80)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x81)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x82)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x83)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x84)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x85)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x86)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x87)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x88)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x89)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x8A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x8B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x8C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x8D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x8E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x8F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x90)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x91)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x92)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x93)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x94)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x95)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x96)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x97)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x98)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x99)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x9A)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x9B)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x9C)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x9D)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x9E)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0x9F)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA0)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA1)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA2)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA3)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA4)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA5)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA6)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA7)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA8)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xA9)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xAA)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xAB)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xAC)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xAD)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xAE)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xAF)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB0)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB1)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB2)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB3)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB4)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB5)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB6)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB7)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB8)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xB9)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xBA)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xBB)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xBC)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xBD)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xBE)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xBF)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC0)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC1)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC2)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC3)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC4)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC5)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC6)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC7)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC8)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xC9)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xCA)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xCB)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xCC)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xCD)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xCE)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xCF)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD0)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD1)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD2)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD3)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD4)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD5)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD6)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD7)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD8)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xD9)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xDA)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xDB)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xDC)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xDD)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xDE)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xDF)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE0)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE1)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE2)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE3)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE4)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE5)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE6)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE7)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE8)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xE9)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xEA)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xEB)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xEC)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xED)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xEE)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xEF)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF0)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF1)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF2)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF3)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF4)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF5)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF6)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF7)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF8)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xF9)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xFA)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xFB)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xFC)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xFD)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xFE)                                         \
    MONAD_COMPILER_ON_EVM_OPCODE(0xFF)
