#!/bin/bash

cmake \
  -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
  -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
  -DCMAKE_C_COMPILER:FILEPATH=clang \
  -DCMAKE_CXX_COMPILER:FILEPATH=clang++ \
  -B build \
  -G Ninja
